version: '3.1'

services:
  db:
    image: mysql:8.0.13
    restart: always
    ports:
      - 3306:3306
    expose:
      - 9898
    environment:
      MYSQL_DATABASE: developer
      MYSQL_USER: warder
      MYSQL_PASSWORD: warder_password
      MYSQL_ROOT_PASSWORD: password
