version: '3.1'

services:
  db:
    image: mysql:8.0.26
    restart: always
    ports:
      - 9898:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: developer