spring:
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:9898/developer
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true