spring:
  datasource:
    username: warder
    password: warder_password
    url: jdbc:mysql://localhost:3306/developer
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db.changelog/db.changelog-master.yml

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLOUD_CLIENT_ID}
            client-secret: ${GOOGLE_CLOUD_CLIENT_SECRET}
            scope: openid, email, profile
            clientAuthenticationScheme: form
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            token-uri: https://www.googleapis.com/oauth2/v4/token
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth

server:
  port: 9000